$folders = @(
    "src/BuildingBlocks/HomeFlow.BuildingBlocks.Domain/Common",
    "src/BuildingBlocks/HomeFlow.BuildingBlocks.Domain/Exceptions",
    "src/BuildingBlocks/HomeFlow.BuildingBlocks.Domain/Events",

    "src/BuildingBlocks/HomeFlow.BuildingBlocks.Application/Abstractions",
    "src/BuildingBlocks/HomeFlow.BuildingBlocks.Application/Behaviors",
    "src/BuildingBlocks/HomeFlow.BuildingBlocks.Application/Results",

    "src/BuildingBlocks/HomeFlow.BuildingBlocks.Infrastructure/Persistence",
    "src/BuildingBlocks/HomeFlow.BuildingBlocks.Infrastructure/DependencyInjection",
    "src/BuildingBlocks/HomeFlow.BuildingBlocks.Infrastructure/Messaging",

    "src/BuildingBlocks/HomeFlow.BuildingBlocks.MultiTenancy/Abstractions",
    "src/BuildingBlocks/HomeFlow.BuildingBlocks.MultiTenancy/Models",
    "src/BuildingBlocks/HomeFlow.BuildingBlocks.MultiTenancy/Services",

    "src/Modules/Identity/HomeFlow.Modules.Identity.Domain/Aggregates",
    "src/Modules/Identity/HomeFlow.Modules.Identity.Domain/Entities",
    "src/Modules/Identity/HomeFlow.Modules.Identity.Domain/ValueObjects",
    "src/Modules/Identity/HomeFlow.Modules.Identity.Domain/Enums",
    "src/Modules/Identity/HomeFlow.Modules.Identity.Domain/Events",
    "src/Modules/Identity/HomeFlow.Modules.Identity.Domain/Repositories",
    "src/Modules/Identity/HomeFlow.Modules.Identity.Domain/Ids",
    "src/Modules/Identity/HomeFlow.Modules.Identity.Application/Commands",
    "src/Modules/Identity/HomeFlow.Modules.Identity.Application/Queries",
    "src/Modules/Identity/HomeFlow.Modules.Identity.Application/DTOs",
    "src/Modules/Identity/HomeFlow.Modules.Identity.Application/Validators",
    "src/Modules/Identity/HomeFlow.Modules.Identity.Application/DependencyInjection",
    "src/Modules/Identity/HomeFlow.Modules.Identity.Infrastructure/Persistence/Configurations",
    "src/Modules/Identity/HomeFlow.Modules.Identity.Infrastructure/Repositories",
    "src/Modules/Identity/HomeFlow.Modules.Identity.Infrastructure/DependencyInjection",
    "src/Modules/Identity/HomeFlow.Modules.Identity.Contracts/Requests",
    "src/Modules/Identity/HomeFlow.Modules.Identity.Contracts/Responses",
    "src/Modules/Identity/HomeFlow.Modules.Identity.Contracts/IntegrationEvents",

    "src/Modules/Tenancy/HomeFlow.Modules.Tenancy.Domain/Aggregates",
    "src/Modules/Tenancy/HomeFlow.Modules.Tenancy.Domain/Entities",
    "src/Modules/Tenancy/HomeFlow.Modules.Tenancy.Domain/ValueObjects",
    "src/Modules/Tenancy/HomeFlow.Modules.Tenancy.Domain/Enums",
    "src/Modules/Tenancy/HomeFlow.Modules.Tenancy.Domain/Events",
    "src/Modules/Tenancy/HomeFlow.Modules.Tenancy.Domain/Repositories",
    "src/Modules/Tenancy/HomeFlow.Modules.Tenancy.Domain/Ids",
    "src/Modules/Tenancy/HomeFlow.Modules.Tenancy.Application/Commands",
    "src/Modules/Tenancy/HomeFlow.Modules.Tenancy.Application/Queries",
    "src/Modules/Tenancy/HomeFlow.Modules.Tenancy.Application/DTOs",
    "src/Modules/Tenancy/HomeFlow.Modules.Tenancy.Application/Validators",
    "src/Modules/Tenancy/HomeFlow.Modules.Tenancy.Application/DependencyInjection",
    "src/Modules/Tenancy/HomeFlow.Modules.Tenancy.Infrastructure/Persistence/Configurations",
    "src/Modules/Tenancy/HomeFlow.Modules.Tenancy.Infrastructure/Repositories",
    "src/Modules/Tenancy/HomeFlow.Modules.Tenancy.Infrastructure/DependencyInjection",
    "src/Modules/Tenancy/HomeFlow.Modules.Tenancy.Contracts/Requests",
    "src/Modules/Tenancy/HomeFlow.Modules.Tenancy.Contracts/Responses",
    "src/Modules/Tenancy/HomeFlow.Modules.Tenancy.Contracts/IntegrationEvents",

    "src/Modules/Subscriptions/HomeFlow.Modules.Subscriptions.Domain/Aggregates",
    "src/Modules/Subscriptions/HomeFlow.Modules.Subscriptions.Domain/Entities",
    "src/Modules/Subscriptions/HomeFlow.Modules.Subscriptions.Domain/ValueObjects",
    "src/Modules/Subscriptions/HomeFlow.Modules.Subscriptions.Domain/Enums",
    "src/Modules/Subscriptions/HomeFlow.Modules.Subscriptions.Domain/Events",
    "src/Modules/Subscriptions/HomeFlow.Modules.Subscriptions.Domain/Repositories",
    "src/Modules/Subscriptions/HomeFlow.Modules.Subscriptions.Domain/Ids",
    "src/Modules/Subscriptions/HomeFlow.Modules.Subscriptions.Application/Commands",
    "src/Modules/Subscriptions/HomeFlow.Modules.Subscriptions.Application/Queries",
    "src/Modules/Subscriptions/HomeFlow.Modules.Subscriptions.Application/DTOs",
    "src/Modules/Subscriptions/HomeFlow.Modules.Subscriptions.Application/Validators",
    "src/Modules/Subscriptions/HomeFlow.Modules.Subscriptions.Application/DependencyInjection",
    "src/Modules/Subscriptions/HomeFlow.Modules.Subscriptions.Infrastructure/Persistence/Configurations",
    "src/Modules/Subscriptions/HomeFlow.Modules.Subscriptions.Infrastructure/Repositories",
    "src/Modules/Subscriptions/HomeFlow.Modules.Subscriptions.Infrastructure/DependencyInjection",
    "src/Modules/Subscriptions/HomeFlow.Modules.Subscriptions.Contracts/Requests",
    "src/Modules/Subscriptions/HomeFlow.Modules.Subscriptions.Contracts/Responses",
    "src/Modules/Subscriptions/HomeFlow.Modules.Subscriptions.Contracts/IntegrationEvents",

    "src/Modules/Households/HomeFlow.Modules.Households.Domain/Aggregates",
    "src/Modules/Households/HomeFlow.Modules.Households.Domain/Entities",
    "src/Modules/Households/HomeFlow.Modules.Households.Domain/ValueObjects",
    "src/Modules/Households/HomeFlow.Modules.Households.Domain/Enums",
    "src/Modules/Households/HomeFlow.Modules.Households.Domain/Events",
    "src/Modules/Households/HomeFlow.Modules.Households.Domain/Repositories",
    "src/Modules/Households/HomeFlow.Modules.Households.Domain/Ids",
    "src/Modules/Households/HomeFlow.Modules.Households.Application/Commands",
    "src/Modules/Households/HomeFlow.Modules.Households.Application/Queries",
    "src/Modules/Households/HomeFlow.Modules.Households.Application/DTOs",
    "src/Modules/Households/HomeFlow.Modules.Households.Application/Validators",
    "src/Modules/Households/HomeFlow.Modules.Households.Application/DependencyInjection",
    "src/Modules/Households/HomeFlow.Modules.Households.Infrastructure/Persistence/Configurations",
    "src/Modules/Households/HomeFlow.Modules.Households.Infrastructure/Repositories",
    "src/Modules/Households/HomeFlow.Modules.Households.Infrastructure/DependencyInjection",
    "src/Modules/Households/HomeFlow.Modules.Households.Contracts/Requests",
    "src/Modules/Households/HomeFlow.Modules.Households.Contracts/Responses",
    "src/Modules/Households/HomeFlow.Modules.Households.Contracts/IntegrationEvents"
)

foreach ($folder in $folders) {
    New-Item -ItemType Directory -Force -Path $folder | Out-Null
}

Write-Host "Folders created." -ForegroundColor Green